export const DEFAULT_DOCUMENT_SETTINGS = {
  businessName: "VadMassage",
  legalName: "",
  ownerName: "Vadim",
  logoUrl: "",
  email: "",
  phone: "",
  website: "",
  addressLine1: "",
  addressLine2: "",
  city: "London",
  postcode: "",
  country: "United Kingdom",
  companyNumber: "",
  utrNumber: "",
  vatNumber: "",
  currency: "GBP",
  taxLabel: "VAT",
  showVat: false,
  showBusinessAddress: true,
  showClientAddress: true,
  receiptPrefix: "VDM",
  invoicePrefix: "INV",
  nextReceiptNumber: "1001",
  nextInvoiceNumber: "1001",
  bookingReferenceLabel: "Booking reference",
  showBookingReference: true,
  showServiceBreakdown: true,
  showTravelCharges: true,
  showPaymentMethod: true,
  sendReceiptAutomatically: true,
  paymentTerms: "Payment due on receipt unless otherwise agreed.",
  invoiceDueDays: "7",
  latePaymentText: "",
  bankName: "",
  bankAccountName: "VadMassage",
  bankSortCode: "",
  bankAccountNumber: "",
  paymentInstructions: "Thank you for your booking.",
  receiptFooter: "Thank you for choosing VadMassage.",
  invoiceFooter: "Please keep this invoice for your records.",
  emailSubject: "Your VadMassage receipt",
  emailIntro: "Thank you for your appointment. Your receipt is attached below.",
  emailReplyTo: "",
  emailCc: "",
  emailSignature: "VadMassage",
  cancellationText: "Free cancellation up to 24 hours before your appointment. Late cancellations may be charged at the therapist's discretion.",
  cancellationNoticeHours: "24",
  cancellationFeeText: "Late cancellations may be charged at the therapist's discretion.",
  noShowText: "Missed appointments may be charged in full.",
};
